//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aspose.Pdf.Builder.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aspose.Pdf.Builder.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arial.
        /// </summary>
        public static string ArialFont {
            get {
                return ResourceManager.GetString("ArialFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arial Unicode MS.
        /// </summary>
        public static string ArialUnicodeFont {
            get {
                return ResourceManager.GetString("ArialUnicodeFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to black.
        /// </summary>
        public static string BlackColor {
            get {
                return ResourceManager.GetString("BlackColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20.0.
        /// </summary>
        public static string BlankRowContactsHeight {
            get {
                return ResourceManager.GetString("BlankRowContactsHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10.0.
        /// </summary>
        public static string BlankRowHeight {
            get {
                return ResourceManager.GetString("BlankRowHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.0.
        /// </summary>
        public static string BlankRowTextAreaHeight {
            get {
                return ResourceManager.GetString("BlankRowTextAreaHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8.
        /// </summary>
        public static string BodyFontSize {
            get {
                return ResourceManager.GetString("BodyFontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.
        /// </summary>
        public static string BulletPointFontSize {
            get {
                return ResourceManager.GetString("BulletPointFontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 225 50.
        /// </summary>
        public static string CheckBoxColumnWidths {
            get {
                return ResourceManager.GetString("CheckBoxColumnWidths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 450.
        /// </summary>
        public static string ColumnSpanFourWidth {
            get {
                return ResourceManager.GetString("ColumnSpanFourWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 350.
        /// </summary>
        public static string ColumnSpanThreeWidth {
            get {
                return ResourceManager.GetString("ColumnSpanThreeWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✘.
        /// </summary>
        public static string CrossLabel {
            get {
                return ResourceManager.GetString("CrossLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bullet5.
        /// </summary>
        public static string DefaultBulletFiveStyle {
            get {
                return ResourceManager.GetString("DefaultBulletFiveStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bullet1.
        /// </summary>
        public static string DefaultBulletStyle {
            get {
                return ResourceManager.GetString("DefaultBulletStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 105.
        /// </summary>
        public static string DefaultColumnSpanOneWidth {
            get {
                return ResourceManager.GetString("DefaultColumnSpanOneWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 450.
        /// </summary>
        public static string DefaultFullWidth {
            get {
                return ResourceManager.GetString("DefaultFullWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arab.
        /// </summary>
        public static string DefaultNumberStyle {
            get {
                return ResourceManager.GetString("DefaultNumberStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100 250 100.
        /// </summary>
        public static string DocumentTypeColumnWidths {
            get {
                return ResourceManager.GetString("DocumentTypeColumnWidths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8.
        /// </summary>
        public static string FooterRowFontSize {
            get {
                return ResourceManager.GetString("FooterRowFontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 605 90.
        /// </summary>
        public static string FooterRowLandscapeColumnWidths {
            get {
                return ResourceManager.GetString("FooterRowLandscapeColumnWidths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 360 90.
        /// </summary>
        public static string FooterRowPortraitColumnWidths {
            get {
                return ResourceManager.GetString("FooterRowPortraitColumnWidths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to © Northern Territory Government of Australia 2014.
        /// </summary>
        public static string FooterRowSignature {
            get {
                return ResourceManager.GetString("FooterRowSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to green.
        /// </summary>
        public static string GreenColor {
            get {
                return ResourceManager.GetString("GreenColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to grey.
        /// </summary>
        public static string GreyColor {
            get {
                return ResourceManager.GetString("GreyColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12.
        /// </summary>
        public static string HeaderFontSize {
            get {
                return ResourceManager.GetString("HeaderFontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #FFFFCC.
        /// </summary>
        public static string HeaderRowBackgroundColor {
            get {
                return ResourceManager.GetString("HeaderRowBackgroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 700.
        /// </summary>
        public static string HeaderRowLandscapeColumnWidths {
            get {
                return ResourceManager.GetString("HeaderRowLandscapeColumnWidths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 470.
        /// </summary>
        public static string HeaderRowPortraitColumnWidths {
            get {
                return ResourceManager.GetString("HeaderRowPortraitColumnWidths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #0494d0.
        /// </summary>
        public static string HeaderTableBackgroundColor {
            get {
                return ResourceManager.GetString("HeaderTableBackgroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7.
        /// </summary>
        public static string HeadingFourFontSize {
            get {
                return ResourceManager.GetString("HeadingFourFontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10.
        /// </summary>
        public static string HeadingOneFontSize {
            get {
                return ResourceManager.GetString("HeadingOneFontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8.
        /// </summary>
        public static string HeadingThreeFontSize {
            get {
                return ResourceManager.GetString("HeadingThreeFontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9.
        /// </summary>
        public static string HeadingTwoFontSize {
            get {
                return ResourceManager.GetString("HeadingTwoFontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Helvetica.
        /// </summary>
        public static string HelveticaFont {
            get {
                return ResourceManager.GetString("HelveticaFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #F5F5F5.
        /// </summary>
        public static string InnerTableColor {
            get {
                return ResourceManager.GetString("InnerTableColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lightgray.
        /// </summary>
        public static string LightGrayColor {
            get {
                return ResourceManager.GetString("LightGrayColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  .
        /// </summary>
        public static string NoneValue {
            get {
                return ResourceManager.GetString("NoneValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string NoValue {
            get {
                return ResourceManager.GetString("NoValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 28.3464567.
        /// </summary>
        public static string OneCm {
            get {
                return ResourceManager.GetString("OneCm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to red.
        /// </summary>
        public static string RedColor {
            get {
                return ResourceManager.GetString("RedColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.0.
        /// </summary>
        public static string ShortBlankRowHeight {
            get {
                return ResourceManager.GetString("ShortBlankRowHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol.
        /// </summary>
        public static string SymbolFont {
            get {
                return ResourceManager.GetString("SymbolFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15.0.
        /// </summary>
        public static string TableBlankRowHeight {
            get {
                return ResourceManager.GetString("TableBlankRowHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 450.
        /// </summary>
        public static string TextAreaColumnWidths {
            get {
                return ResourceManager.GetString("TextAreaColumnWidths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 60.0.
        /// </summary>
        public static string TextAreaRowHeight {
            get {
                return ResourceManager.GetString("TextAreaRowHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to white.
        /// </summary>
        public static string WhiteColor {
            get {
                return ResourceManager.GetString("WhiteColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string YesValue {
            get {
                return ResourceManager.GetString("YesValue", resourceCulture);
            }
        }
    }
}
